language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: zwbmJWqhOLAHi+Nase0QlSjlBzKQdkUzSR1hKfk9QiFvwNCuty2sC0/oRVix4/GdZMa0ywk/ni+N8ZBQf591b/7nqZmhBHpEcmnX2tvgiosKPGe3BIofpNU6BvJrlWu6aC5NN1895UFY66czyL3UY9XI7m1RlqaPU+Smnb/U8lfkmO8+ch4NBfZurntRNi51r+GgeSu3u93ge/t+O8WGjoxWPGUsASlJu5exsj0ZuDjiIxgDlZEp3AZbDWQgOBOECqtSWuf2fVWo9Ze2ttDzr0gAiyNnlwyjvw3WhwYVR7SaYb/fe0iwP6JTD7EZZblbid/cT25TVRN4HZ3UUF+ayt4u8XX822oGBaD3N1n6k1rVnJPYY6ctkf8DyONBZfF7l1DjfQaWaZwa8xTvjOuqYzgBJn2UOIyK1jWI2kc5DQGriUiJJHJKJJk703VKccCJ12QEj41qAmZU1Spwgqb0iEzELnIJqU7Emz8Cd3TYFDHRVBGZnHFDJ9xlIIU5GgV/kYz7TlOmuQdjIqMCISvlg3aN84JFN/z0RnBQb6lHM5Prw4fc2TsteUv91JuMtIJhwMDZpFNClMfxiczA70DdSsJazoau9gdq2NtvQFLVCFiIVvCkV9Brq7KLWE7EtCku+vUjj5CxzhJRWaQwU72+7Muj/JGkDlr0P95XYOFQK9k=
  app: nameless-falls-45512
  on:
    repo: antonvictorio/phoenix_api
